/**
 * Concierge — Security Headers
 *
 * Centralised security header definitions applied by Edge middleware
 * to every response. Follows OWASP Secure Headers Project guidelines.
 *
 * @see https://owasp.org/www-project-secure-headers/
 */

import { env } from '@/lib/env';

// ---------------------------------------------------------------------------
// CORS Configuration
// ---------------------------------------------------------------------------

const CORS_METHODS = 'GET, POST, PATCH, DELETE, OPTIONS';
const CORS_HEADERS = 'Content-Type, Authorization, X-Request-ID';
const CORS_MAX_AGE = '86400'; // 24 hours

/**
 * Returns CORS headers for a given origin and HTTP method.
 *
 * Only origins listed in `CORS_ORIGINS` (env) receive the
 * `Access-Control-Allow-Origin` header. Unrecognised origins get
 * an empty object — the browser will block the cross-origin request.
 *
 * @param origin  - The value of the `Origin` request header.
 * @param method  - The HTTP method (used to detect preflight).
 * @returns A plain object mapping header names to their values.
 */
export function getCorsHeaders(
  origin: string | null | undefined,
  method: string,
): Record<string, string> {
  // No origin header means same-origin or non-browser request — skip CORS.
  if (!origin) return {};

  // In development, allow all localhost origins
  if (process.env.NODE_ENV !== 'production') {
    if (!origin.startsWith('http://localhost')) return {};
  } else {
    let allowedOrigins: string[];
    try {
      allowedOrigins = env?.CORS_ORIGINS ?? [];
    } catch {
      allowedOrigins = [];
    }
    if (!allowedOrigins.includes(origin)) return {};
  }

  const headers: Record<string, string> = {
    'Access-Control-Allow-Origin': origin,
    'Access-Control-Allow-Credentials': 'true',
    Vary: 'Origin',
  };

  // Preflight requests get the full set of CORS response headers.
  if (method === 'OPTIONS') {
    headers['Access-Control-Allow-Methods'] = CORS_METHODS;
    headers['Access-Control-Allow-Headers'] = CORS_HEADERS;
    headers['Access-Control-Max-Age'] = CORS_MAX_AGE;
  }

  return headers;
}

// ---------------------------------------------------------------------------
// Content Security Policy Builder
// ---------------------------------------------------------------------------

/**
 * Build a Content-Security-Policy header value with a per-request nonce.
 *
 * The nonce is injected into `script-src` so only scripts generated by
 * our server (with the matching nonce attribute) can execute.
 *
 * `style-src 'unsafe-inline'` is kept for now because Tailwind CSS and
 * many component libraries inject inline styles. This will be tightened
 * once we move to a nonce-based style strategy.
 */
function buildCsp(nonce: string): string {
  const isDev = process.env.NODE_ENV === 'development';

  const directives: string[] = [
    "default-src 'self'",
    isDev ? `script-src 'self' 'unsafe-eval' 'unsafe-inline'` : `script-src 'self' 'unsafe-inline'`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: https:",
    "font-src 'self'",
    isDev ? "connect-src 'self' wss: ws: http://localhost:*" : "connect-src 'self' wss:",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
    ...(isDev ? [] : ['upgrade-insecure-requests']),
  ];

  return directives.join('; ');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns all security headers that should be set on every HTTP response.
 *
 * @param nonce - A cryptographically random base64 string generated per request.
 * @returns A plain object mapping header names to their values.
 */
export function getSecurityHeaders(nonce: string): Record<string, string> {
  const isDev = process.env.NODE_ENV === 'development';

  const headers: Record<string, string> = {
    'Content-Security-Policy': buildCsp(nonce),
    'X-Frame-Options': 'DENY',
    'X-Content-Type-Options': 'nosniff',
    'X-XSS-Protection': '0',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=()',
    'X-DNS-Prefetch-Control': 'off',
    'Cache-Control': 'no-store, no-cache, must-revalidate',
  };

  if (!isDev) {
    headers['Strict-Transport-Security'] = 'max-age=31536000; includeSubDomains; preload';
    headers['Cross-Origin-Opener-Policy'] = 'same-origin-allow-popups';
    headers['Cross-Origin-Resource-Policy'] = 'same-site';
  }

  return headers;
}
