/**
 * Concierge — Security Headers
 *
 * Centralised security header definitions applied by Edge middleware
 * to every response. Follows OWASP Secure Headers Project guidelines.
 *
 * @see https://owasp.org/www-project-secure-headers/
 */

// ---------------------------------------------------------------------------
// Content Security Policy Builder
// ---------------------------------------------------------------------------

/**
 * Build a Content-Security-Policy header value with a per-request nonce.
 *
 * The nonce is injected into `script-src` so only scripts generated by
 * our server (with the matching nonce attribute) can execute.
 *
 * `style-src 'unsafe-inline'` is kept for now because Tailwind CSS and
 * many component libraries inject inline styles. This will be tightened
 * once we move to a nonce-based style strategy.
 */
function buildCsp(nonce: string): string {
  const directives: string[] = [
    "default-src 'self'",
    `script-src 'self' 'nonce-${nonce}'`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: https:",
    "font-src 'self'",
    "connect-src 'self' wss:",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
    'upgrade-insecure-requests',
  ];

  return directives.join('; ');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns all security headers that should be set on every HTTP response.
 *
 * @param nonce - A cryptographically random base64 string generated per request.
 * @returns A plain object mapping header names to their values.
 */
export function getSecurityHeaders(nonce: string): Record<string, string> {
  return {
    'Content-Security-Policy': buildCsp(nonce),
    'X-Frame-Options': 'DENY',
    'X-Content-Type-Options': 'nosniff',
    'X-XSS-Protection': '0',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=()',
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
    'X-DNS-Prefetch-Control': 'off',
    'Cross-Origin-Opener-Policy': 'same-origin',
    'Cross-Origin-Resource-Policy': 'same-origin',
    'Cross-Origin-Embedder-Policy': 'require-corp',
    'Cache-Control': 'no-store, no-cache, must-revalidate',
  };
}
