/**
 * Rich demo data for sales presentations.
 *
 * All timestamps are relative to Date.now() so the data always looks fresh.
 * UUIDs match prisma/seed.ts so the hardcoded demo property resolves.
 */

import type { DemoDataStore } from './demo-data-store';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function uuid(suffix: string) {
  return `00000000-0000-4000-d000-${suffix.padStart(12, '0')}`;
}

function ago(hours: number): string {
  return new Date(Date.now() - hours * 3600_000).toISOString();
}

function future(hours: number): string {
  return new Date(Date.now() + hours * 3600_000).toISOString();
}

function today(hour: number, min = 0): string {
  const d = new Date();
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
}

// Stable IDs matching prisma/seed.ts
const IDS = {
  superAdmin: '00000000-0000-4000-a000-000000000001',
  mapleHeights: '00000000-0000-4000-b000-000000000001',
  lakeshoreTowers: '00000000-0000-4000-b000-000000000002',
  harbourfront: '00000000-0000-4000-b000-000000000003',
};

// ---------------------------------------------------------------------------
// Seed function
// ---------------------------------------------------------------------------

export function seedDemoData(store: DemoDataStore) {
  // =========================================================================
  // PROPERTIES
  // =========================================================================
  store.seed('properties', [
    {
      id: IDS.mapleHeights,
      name: 'Maple Heights Condominiums',
      address: '100 Maple Avenue',
      city: 'Toronto',
      province: 'Ontario',
      country: 'CA',
      postalCode: 'M5V 2H1',
      unitCount: 200,
      timezone: 'America/Toronto',
      logo: null,
      type: 'PRODUCTION',
      subscriptionTier: 'TIER_2',
      slug: 'maple-heights',
      branding: { accentColor: '#1e40af' },
      propertyCode: 'MH2024A',
      isActive: true,
      createdAt: ago(2160), // ~90 days ago
    },
    {
      id: IDS.lakeshoreTowers,
      name: 'Lakeshore Towers',
      address: '450 Lakeshore Blvd W',
      city: 'Toronto',
      province: 'Ontario',
      country: 'CA',
      postalCode: 'M5V 1A3',
      unitCount: 150,
      timezone: 'America/Toronto',
      logo: null,
      type: 'PRODUCTION',
      subscriptionTier: 'TIER_1',
      slug: 'lakeshore-towers',
      branding: { accentColor: '#059669' },
      propertyCode: 'LT2024B',
      isActive: true,
      createdAt: ago(1440), // ~60 days ago
    },
    {
      id: IDS.harbourfront,
      name: 'Harbourfront Residences',
      address: '88 Harbour Street',
      city: 'Toronto',
      province: 'Ontario',
      country: 'CA',
      postalCode: 'M5J 1B7',
      unitCount: 320,
      timezone: 'America/Toronto',
      logo: null,
      type: 'PRODUCTION',
      subscriptionTier: 'TIER_3',
      slug: 'harbourfront-residences',
      branding: { accentColor: '#7c3aed' },
      propertyCode: 'HR2024C',
      isActive: true,
      createdAt: ago(720), // ~30 days ago
    },
  ]);

  // =========================================================================
  // USERS (40+ across roles)
  // =========================================================================
  const users = [
    // --- Super Admin ---
    {
      id: IDS.superAdmin,
      email: 'admin@concierge.app',
      firstName: 'Platform',
      lastName: 'Admin',
      phone: '+1-416-555-0001',
      role: { id: uuid('r01'), name: 'Super Admin', slug: 'super_admin' },
      status: 'active',
      isActive: true,
      mfaEnabled: true,
      lastLoginAt: ago(0.5),
      createdAt: ago(2160),
    },
    // --- Maple Heights Staff ---
    {
      id: uuid('u02'),
      email: 'sarah.chen@mapleheights.ca',
      firstName: 'Sarah',
      lastName: 'Chen',
      phone: '+1-416-555-0102',
      role: { id: uuid('r02'), name: 'Property Manager', slug: 'property_manager' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: true,
      lastLoginAt: ago(1),
      createdAt: ago(2100),
    },
    {
      id: uuid('u03'),
      email: 'mike.johnson@mapleheights.ca',
      firstName: 'Mike',
      lastName: 'Johnson',
      phone: '+1-416-555-0103',
      role: { id: uuid('r03'), name: 'Front Desk', slug: 'front_desk' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: false,
      lastLoginAt: ago(2),
      createdAt: ago(1800),
    },
    {
      id: uuid('u04'),
      email: 'guard.patel@mapleheights.ca',
      firstName: 'Raj',
      lastName: 'Patel',
      phone: '+1-416-555-0104',
      role: { id: uuid('r04'), name: 'Security Guard', slug: 'security_guard' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: false,
      lastLoginAt: ago(4),
      createdAt: ago(1500),
    },
    {
      id: uuid('u05'),
      email: 'tony.maint@mapleheights.ca',
      firstName: 'Tony',
      lastName: 'DiMaggio',
      phone: '+1-416-555-0105',
      role: { id: uuid('r05'), name: 'Maintenance Staff', slug: 'maintenance_staff' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: false,
      lastLoginAt: ago(6),
      createdAt: ago(1200),
    },
    {
      id: uuid('u06'),
      email: 'priya.super@mapleheights.ca',
      firstName: 'Priya',
      lastName: 'Sharma',
      phone: '+1-416-555-0106',
      role: { id: uuid('r06'), name: 'Superintendent', slug: 'superintendent' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: true,
      lastLoginAt: ago(3),
      createdAt: ago(2000),
    },
    {
      id: uuid('u07'),
      email: 'night.shift@mapleheights.ca',
      firstName: 'James',
      lastName: 'Wu',
      phone: '+1-416-555-0107',
      role: { id: uuid('r03'), name: 'Front Desk', slug: 'front_desk' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: false,
      lastLoginAt: ago(12),
      createdAt: ago(900),
    },
    // --- Maple Heights Residents ---
    {
      id: uuid('u10'),
      email: 'lisa.wang@gmail.com',
      firstName: 'Lisa',
      lastName: 'Wang',
      phone: '+1-416-555-0210',
      role: { id: uuid('r10'), name: 'Resident Owner', slug: 'resident_owner' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: false,
      lastLoginAt: ago(8),
      createdAt: ago(1800),
    },
    {
      id: uuid('u11'),
      email: 'david.kumar@outlook.com',
      firstName: 'David',
      lastName: 'Kumar',
      phone: '+1-416-555-0211',
      role: { id: uuid('r11'), name: 'Resident Tenant', slug: 'resident_tenant' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: false,
      lastLoginAt: ago(24),
      createdAt: ago(1200),
    },
    {
      id: uuid('u12'),
      email: 'maria.garcia@yahoo.com',
      firstName: 'Maria',
      lastName: 'Garcia',
      phone: '+1-416-555-0212',
      role: { id: uuid('r10'), name: 'Resident Owner', slug: 'resident_owner' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: false,
      lastLoginAt: ago(48),
      createdAt: ago(1500),
    },
    {
      id: uuid('u13'),
      email: 'robert.smith@gmail.com',
      firstName: 'Robert',
      lastName: 'Smith',
      phone: '+1-416-555-0213',
      role: { id: uuid('r11'), name: 'Resident Tenant', slug: 'resident_tenant' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: false,
      lastLoginAt: ago(72),
      createdAt: ago(1000),
    },
    {
      id: uuid('u14'),
      email: 'jennifer.lee@hotmail.com',
      firstName: 'Jennifer',
      lastName: 'Lee',
      phone: '+1-416-555-0214',
      role: { id: uuid('r10'), name: 'Resident Owner', slug: 'resident_owner' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: true,
      lastLoginAt: ago(2),
      createdAt: ago(1700),
    },
    {
      id: uuid('u15'),
      email: 'alex.thompson@gmail.com',
      firstName: 'Alex',
      lastName: 'Thompson',
      phone: '+1-416-555-0215',
      role: { id: uuid('r11'), name: 'Resident Tenant', slug: 'resident_tenant' },
      propertyId: IDS.mapleHeights,
      status: 'pending',
      isActive: false,
      mfaEnabled: false,
      lastLoginAt: null,
      createdAt: ago(48),
    },
    // --- Maple Heights Board ---
    {
      id: uuid('u20'),
      email: 'board.chair@mapleheights.ca',
      firstName: 'Eleanor',
      lastName: 'Mitchell',
      phone: '+1-416-555-0220',
      role: { id: uuid('r20'), name: 'Board Member', slug: 'board_member' },
      propertyId: IDS.mapleHeights,
      status: 'active',
      isActive: true,
      mfaEnabled: true,
      lastLoginAt: ago(24),
      createdAt: ago(2000),
    },
    // --- Lakeshore Staff ---
    {
      id: uuid('u30'),
      email: 'pm@lakeshoretowers.ca',
      firstName: 'Anna',
      lastName: 'Petrova',
      phone: '+1-416-555-0300',
      role: { id: uuid('r02'), name: 'Property Manager', slug: 'property_manager' },
      propertyId: IDS.lakeshoreTowers,
      status: 'active',
      isActive: true,
      mfaEnabled: true,
      lastLoginAt: ago(3),
      createdAt: ago(1400),
    },
    {
      id: uuid('u31'),
      email: 'fd@lakeshoretowers.ca',
      firstName: 'Carlos',
      lastName: 'Rivera',
      phone: '+1-416-555-0301',
      role: { id: uuid('r03'), name: 'Front Desk', slug: 'front_desk' },
      propertyId: IDS.lakeshoreTowers,
      status: 'active',
      isActive: true,
      mfaEnabled: false,
      lastLoginAt: ago(5),
      createdAt: ago(1000),
    },
    // --- Harbourfront Staff ---
    {
      id: uuid('u40'),
      email: 'pm@harbourfront.ca',
      firstName: 'Olivia',
      lastName: 'Nguyen',
      phone: '+1-416-555-0400',
      role: { id: uuid('r02'), name: 'Property Manager', slug: 'property_manager' },
      propertyId: IDS.harbourfront,
      status: 'active',
      isActive: true,
      mfaEnabled: true,
      lastLoginAt: ago(1),
      createdAt: ago(700),
    },
    {
      id: uuid('u41'),
      email: 'fd@harbourfront.ca',
      firstName: 'Marcus',
      lastName: 'Brown',
      phone: '+1-416-555-0401',
      role: { id: uuid('r03'), name: 'Front Desk', slug: 'front_desk' },
      propertyId: IDS.harbourfront,
      status: 'active',
      isActive: true,
      mfaEnabled: false,
      lastLoginAt: ago(2),
      createdAt: ago(600),
    },
  ];
  store.seed('users', users);

  // =========================================================================
  // UNITS (20 for Maple Heights)
  // =========================================================================
  const units = [];
  const bldgId = uuid('bld01');
  for (let floor = 1; floor <= 5; floor++) {
    for (let u = 1; u <= 4; u++) {
      const num = floor * 100 + u;
      units.push({
        id: uuid(`unit${String(num).padStart(4, '0')}`),
        propertyId: IDS.mapleHeights,
        number: String(num),
        floor,
        status: num === 502 ? 'vacant' : num === 403 ? 'maintenance' : 'occupied',
        unitType: u <= 2 ? '2 Bedroom' : u === 3 ? '1 Bedroom' : 'Studio',
        buildingId: bldgId,
        building: { id: bldgId, name: 'Main Tower' },
        unitInstructions:
          num === 301
            ? [
                {
                  id: uuid('ui01'),
                  instructionText: 'Friendly golden retriever — ring doorbell twice.',
                  priority: 'high',
                },
              ]
            : num === 204
              ? [
                  {
                    id: uuid('ui02'),
                    instructionText: 'Hard of hearing. Knock firmly.',
                    priority: 'medium',
                  },
                ]
              : [],
        deletedAt: null,
        createdAt: ago(2160),
      });
    }
  }
  store.seed('units', units);

  // =========================================================================
  // COURIERS
  // =========================================================================
  const couriers = [
    { id: uuid('cour01'), name: 'Amazon', iconUrl: null, color: '#FF9900' },
    { id: uuid('cour02'), name: 'FedEx', iconUrl: null, color: '#4D148C' },
    { id: uuid('cour03'), name: 'UPS', iconUrl: null, color: '#351C15' },
    { id: uuid('cour04'), name: 'Canada Post', iconUrl: null, color: '#E00000' },
    { id: uuid('cour05'), name: 'DHL', iconUrl: null, color: '#FFCC00' },
    { id: uuid('cour06'), name: 'Purolator', iconUrl: null, color: '#B31942' },
    { id: uuid('cour07'), name: 'Other', iconUrl: null, color: '#6B7280' },
  ];
  store.seed('couriers', couriers);

  // =========================================================================
  // PACKAGES (25+)
  // =========================================================================
  store.seed('packages', [
    {
      id: uuid('pkg01'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0101'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2401',
      trackingNumber: '1Z999AA10123456784',
      status: 'unreleased',
      isPerishable: false,
      isOversized: false,
      notifyChannel: 'email',
      createdById: uuid('u03'),
      createdAt: ago(0.5),
      releasedAt: null,
      unit: { id: uuid('unit0101'), number: '101' },
      courier: couriers[0],
      storageSpot: { id: uuid('ss01'), name: 'Shelf A', code: 'SA' },
      parcelCategory: null,
    },
    {
      id: uuid('pkg02'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0102'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2402',
      trackingNumber: '789456123789456123',
      status: 'unreleased',
      isPerishable: true,
      isOversized: false,
      notifyChannel: 'sms',
      createdById: uuid('u03'),
      createdAt: ago(1),
      releasedAt: null,
      unit: { id: uuid('unit0102'), number: '102' },
      courier: couriers[1],
      storageSpot: { id: uuid('ss02'), name: 'Fridge', code: 'FR' },
      parcelCategory: { id: uuid('pc01'), name: 'Food & Beverages' },
    },
    {
      id: uuid('pkg03'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0201'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2403',
      trackingNumber: null,
      status: 'unreleased',
      isPerishable: false,
      isOversized: true,
      notifyChannel: 'email',
      createdById: uuid('u03'),
      createdAt: ago(2),
      releasedAt: null,
      unit: { id: uuid('unit0201'), number: '201' },
      courier: couriers[2],
      storageSpot: { id: uuid('ss03'), name: 'Loading Dock', code: 'LD' },
      parcelCategory: null,
    },
    {
      id: uuid('pkg04'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0202'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2404',
      trackingNumber: 'CP123456789CA',
      status: 'unreleased',
      isPerishable: false,
      isOversized: false,
      notifyChannel: 'push',
      createdById: uuid('u07'),
      createdAt: ago(3),
      releasedAt: null,
      unit: { id: uuid('unit0202'), number: '202' },
      courier: couriers[3],
      storageSpot: { id: uuid('ss01'), name: 'Shelf A', code: 'SA' },
      parcelCategory: null,
    },
    {
      id: uuid('pkg05'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0301'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2405',
      trackingNumber: '1Z999BB20987654321',
      status: 'unreleased',
      isPerishable: true,
      isOversized: false,
      notifyChannel: 'email',
      createdById: uuid('u03'),
      createdAt: ago(0.25),
      releasedAt: null,
      unit: { id: uuid('unit0301'), number: '301' },
      courier: couriers[0],
      storageSpot: { id: uuid('ss02'), name: 'Fridge', code: 'FR' },
      parcelCategory: { id: uuid('pc01'), name: 'Food & Beverages' },
    },
    {
      id: uuid('pkg06'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0302'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2406',
      trackingNumber: 'DHL4567891234',
      status: 'unreleased',
      isPerishable: false,
      isOversized: false,
      notifyChannel: 'email',
      createdById: uuid('u03'),
      createdAt: ago(4),
      releasedAt: null,
      unit: { id: uuid('unit0302'), number: '302' },
      courier: couriers[4],
      storageSpot: { id: uuid('ss01'), name: 'Shelf A', code: 'SA' },
      parcelCategory: null,
    },
    {
      id: uuid('pkg07'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0303'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2407',
      trackingNumber: 'PUR987654321',
      status: 'unreleased',
      isPerishable: false,
      isOversized: false,
      notifyChannel: 'sms',
      createdById: uuid('u07'),
      createdAt: ago(5),
      releasedAt: null,
      unit: { id: uuid('unit0303'), number: '303' },
      courier: couriers[5],
      storageSpot: { id: uuid('ss04'), name: 'Shelf B', code: 'SB' },
      parcelCategory: null,
    },
    {
      id: uuid('pkg08'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0304'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2408',
      trackingNumber: '1Z999CC30456789012',
      status: 'unreleased',
      isPerishable: false,
      isOversized: false,
      notifyChannel: 'email',
      createdById: uuid('u03'),
      createdAt: ago(6),
      releasedAt: null,
      unit: { id: uuid('unit0304'), number: '304' },
      courier: couriers[0],
      storageSpot: { id: uuid('ss01'), name: 'Shelf A', code: 'SA' },
      parcelCategory: null,
    },
    // Released packages
    {
      id: uuid('pkg10'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0101'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2410',
      trackingNumber: '1Z888AA10111222333',
      status: 'released',
      isPerishable: false,
      isOversized: false,
      notifyChannel: 'email',
      createdById: uuid('u03'),
      createdAt: ago(24),
      releasedAt: ago(20),
      unit: { id: uuid('unit0101'), number: '101' },
      courier: couriers[0],
      storageSpot: null,
      parcelCategory: null,
    },
    {
      id: uuid('pkg11'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0201'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2411',
      trackingNumber: 'FX444555666',
      status: 'released',
      isPerishable: false,
      isOversized: false,
      notifyChannel: 'email',
      createdById: uuid('u07'),
      createdAt: ago(48),
      releasedAt: ago(44),
      unit: { id: uuid('unit0201'), number: '201' },
      courier: couriers[1],
      storageSpot: null,
      parcelCategory: null,
    },
    {
      id: uuid('pkg12'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0302'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2412',
      trackingNumber: 'UPS777888999',
      status: 'released',
      isPerishable: false,
      isOversized: true,
      notifyChannel: 'sms',
      createdById: uuid('u03'),
      createdAt: ago(72),
      releasedAt: ago(68),
      unit: { id: uuid('unit0302'), number: '302' },
      courier: couriers[2],
      storageSpot: null,
      parcelCategory: null,
    },
    {
      id: uuid('pkg13'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0401'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2413',
      trackingNumber: null,
      status: 'released',
      isPerishable: false,
      isOversized: false,
      notifyChannel: 'email',
      createdById: uuid('u03'),
      createdAt: ago(96),
      releasedAt: ago(90),
      unit: { id: uuid('unit0401'), number: '401' },
      courier: couriers[6],
      storageSpot: null,
      parcelCategory: null,
    },
    {
      id: uuid('pkg14'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0402'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2414',
      trackingNumber: 'AMZ111222333',
      status: 'released',
      isPerishable: true,
      isOversized: false,
      notifyChannel: 'push',
      createdById: uuid('u07'),
      createdAt: ago(120),
      releasedAt: ago(116),
      unit: { id: uuid('unit0402'), number: '402' },
      courier: couriers[0],
      storageSpot: null,
      parcelCategory: { id: uuid('pc01'), name: 'Food & Beverages' },
    },
    // Returned
    {
      id: uuid('pkg20'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0501'),
      direction: 'inbound',
      referenceNumber: 'PKG-MH2420',
      trackingNumber: 'RET123456789',
      status: 'returned',
      isPerishable: false,
      isOversized: false,
      notifyChannel: 'email',
      createdById: uuid('u03'),
      createdAt: ago(168),
      releasedAt: null,
      unit: { id: uuid('unit0501'), number: '501' },
      courier: couriers[3],
      storageSpot: null,
      parcelCategory: null,
    },
  ]);

  // =========================================================================
  // MAINTENANCE CATEGORIES
  // =========================================================================
  const maintCategories = [
    { id: uuid('mc01'), name: 'Plumbing', propertyId: IDS.mapleHeights },
    { id: uuid('mc02'), name: 'Electrical', propertyId: IDS.mapleHeights },
    { id: uuid('mc03'), name: 'HVAC', propertyId: IDS.mapleHeights },
    { id: uuid('mc04'), name: 'Appliance', propertyId: IDS.mapleHeights },
    { id: uuid('mc05'), name: 'General', propertyId: IDS.mapleHeights },
    { id: uuid('mc06'), name: 'Pest Control', propertyId: IDS.mapleHeights },
  ];
  store.seed('maintenanceCategories', maintCategories);

  // =========================================================================
  // MAINTENANCE REQUESTS (15+)
  // =========================================================================
  store.seed('maintenance', [
    {
      id: uuid('mr01'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0301'),
      categoryId: uuid('mc01'),
      status: 'open',
      priority: 'high',
      title: 'Kitchen sink leaking',
      description: 'Water dripping from the kitchen faucet since yesterday. Getting worse.',
      referenceNumber: 'MR-MH0001',
      permissionToEnter: 'yes',
      entryInstructions: 'Dog is friendly. Ring doorbell twice.',
      residentId: uuid('u10'),
      hideFromResident: false,
      createdAt: ago(6),
      completedDate: null,
      unit: { id: uuid('unit0301'), number: '301' },
      category: { id: uuid('mc01'), name: 'Plumbing' },
    },
    {
      id: uuid('mr02'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0204'),
      categoryId: uuid('mc02'),
      status: 'in_progress',
      priority: 'medium',
      title: 'Flickering hallway light',
      description: 'The light in the hallway near the entrance flickers intermittently.',
      referenceNumber: 'MR-MH0002',
      permissionToEnter: 'yes',
      entryInstructions: null,
      residentId: uuid('u11'),
      hideFromResident: false,
      createdAt: ago(24),
      completedDate: null,
      unit: { id: uuid('unit0204'), number: '204' },
      category: { id: uuid('mc02'), name: 'Electrical' },
    },
    {
      id: uuid('mr03'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0102'),
      categoryId: uuid('mc03'),
      status: 'open',
      priority: 'urgent',
      title: 'No heating in unit',
      description: 'Heating system stopped working completely. Temperature dropping.',
      referenceNumber: 'MR-MH0003',
      permissionToEnter: 'yes',
      entryInstructions: 'Key under welcome mat',
      residentId: uuid('u12'),
      hideFromResident: false,
      createdAt: ago(3),
      completedDate: null,
      unit: { id: uuid('unit0102'), number: '102' },
      category: { id: uuid('mc03'), name: 'HVAC' },
    },
    {
      id: uuid('mr04'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0401'),
      categoryId: uuid('mc04'),
      status: 'on_hold',
      priority: 'low',
      title: 'Dishwasher not draining',
      description: 'Dishwasher leaves standing water after each cycle. Waiting for parts.',
      referenceNumber: 'MR-MH0004',
      permissionToEnter: 'yes',
      entryInstructions: null,
      residentId: uuid('u13'),
      hideFromResident: false,
      createdAt: ago(72),
      completedDate: null,
      unit: { id: uuid('unit0401'), number: '401' },
      category: { id: uuid('mc04'), name: 'Appliance' },
    },
    {
      id: uuid('mr05'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0501'),
      categoryId: uuid('mc05'),
      status: 'open',
      priority: 'medium',
      title: 'Balcony door seal damaged',
      description: 'Cold air coming through the seal around the balcony door.',
      referenceNumber: 'MR-MH0005',
      permissionToEnter: 'no',
      entryInstructions: null,
      residentId: uuid('u14'),
      hideFromResident: false,
      createdAt: ago(48),
      completedDate: null,
      unit: { id: uuid('unit0501'), number: '501' },
      category: { id: uuid('mc05'), name: 'General' },
    },
    {
      id: uuid('mr06'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0303'),
      categoryId: uuid('mc06'),
      status: 'in_progress',
      priority: 'high',
      title: 'Ant infestation in kitchen',
      description:
        'Finding ants around the kitchen counter and under the sink. Pest control scheduled.',
      referenceNumber: 'MR-MH0006',
      permissionToEnter: 'yes',
      entryInstructions: 'Can enter during work hours 9-5',
      residentId: uuid('u10'),
      hideFromResident: false,
      createdAt: ago(36),
      completedDate: null,
      unit: { id: uuid('unit0303'), number: '303' },
      category: { id: uuid('mc06'), name: 'Pest Control' },
    },
    // Resolved
    {
      id: uuid('mr07'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0201'),
      categoryId: uuid('mc01'),
      status: 'resolved',
      priority: 'medium',
      title: 'Toilet running constantly',
      description: 'Toilet in main bathroom runs non-stop. Flapper valve replaced.',
      referenceNumber: 'MR-MH0007',
      permissionToEnter: 'yes',
      entryInstructions: null,
      residentId: uuid('u11'),
      hideFromResident: false,
      createdAt: ago(168),
      completedDate: ago(144),
      unit: { id: uuid('unit0201'), number: '201' },
      category: { id: uuid('mc01'), name: 'Plumbing' },
    },
    {
      id: uuid('mr08'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0101'),
      categoryId: uuid('mc02'),
      status: 'closed',
      priority: 'low',
      title: 'Outlet not working in bedroom',
      description: 'Wall outlet on the east wall has no power. Breaker was tripped.',
      referenceNumber: 'MR-MH0008',
      permissionToEnter: 'yes',
      entryInstructions: null,
      residentId: uuid('u10'),
      hideFromResident: false,
      createdAt: ago(240),
      completedDate: ago(216),
      unit: { id: uuid('unit0101'), number: '101' },
      category: { id: uuid('mc02'), name: 'Electrical' },
    },
    {
      id: uuid('mr09'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0402'),
      categoryId: uuid('mc03'),
      status: 'resolved',
      priority: 'high',
      title: 'AC unit making loud noise',
      description: 'Air conditioning unit started making a grinding noise. Compressor replaced.',
      referenceNumber: 'MR-MH0009',
      permissionToEnter: 'yes',
      entryInstructions: null,
      residentId: uuid('u13'),
      hideFromResident: false,
      createdAt: ago(336),
      completedDate: ago(288),
      unit: { id: uuid('unit0402'), number: '402' },
      category: { id: uuid('mc03'), name: 'HVAC' },
    },
    {
      id: uuid('mr10'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0304'),
      categoryId: uuid('mc05'),
      status: 'closed',
      priority: 'low',
      title: 'Paint chipping in hallway',
      description: 'Paint chipping near the front door. Touched up during scheduled maintenance.',
      referenceNumber: 'MR-MH0010',
      permissionToEnter: 'not_applicable',
      entryInstructions: null,
      residentId: null,
      hideFromResident: false,
      createdAt: ago(480),
      completedDate: ago(456),
      unit: { id: uuid('unit0304'), number: '304' },
      category: { id: uuid('mc05'), name: 'General' },
    },
  ]);

  // =========================================================================
  // AMENITIES
  // =========================================================================
  const amenityGroup = { id: uuid('ag01'), name: 'Recreation' };
  store.seed('amenityGroups', [amenityGroup, { id: uuid('ag02'), name: 'Function Rooms' }]);
  store.seed('amenities', [
    {
      id: uuid('am01'),
      propertyId: IDS.mapleHeights,
      groupId: uuid('ag01'),
      name: 'Fitness Centre',
      description: 'Fully equipped gym with cardio equipment, free weights, and stretching area.',
      capacity: 30,
      imageUrl: null,
      group: amenityGroup,
      bookings: [
        {
          id: uuid('bk01'),
          startDate: today(9),
          endDate: today(9),
          startTime: '09:00',
          endTime: '11:00',
          status: 'approved',
        },
      ],
      deletedAt: null,
    },
    {
      id: uuid('am02'),
      propertyId: IDS.mapleHeights,
      groupId: uuid('ag01'),
      name: 'Swimming Pool',
      description: 'Indoor heated pool with lane swimming. 25m length.',
      capacity: 20,
      imageUrl: null,
      group: amenityGroup,
      bookings: [
        {
          id: uuid('bk02'),
          startDate: today(14),
          endDate: today(14),
          startTime: '14:00',
          endTime: '16:00',
          status: 'approved',
        },
      ],
      deletedAt: null,
    },
    {
      id: uuid('am03'),
      propertyId: IDS.mapleHeights,
      groupId: uuid('ag02'),
      name: 'Party Room',
      description: 'Spacious event room with kitchen, seating for 60, and AV setup.',
      capacity: 60,
      imageUrl: null,
      group: { id: uuid('ag02'), name: 'Function Rooms' },
      bookings: [
        {
          id: uuid('bk03'),
          startDate: future(48),
          endDate: future(48),
          startTime: '18:00',
          endTime: '22:00',
          status: 'pending',
        },
      ],
      deletedAt: null,
    },
    {
      id: uuid('am04'),
      propertyId: IDS.mapleHeights,
      groupId: uuid('ag01'),
      name: 'Rooftop Lounge',
      description: 'Open-air lounge with BBQ grills, seating, and skyline views.',
      capacity: 40,
      imageUrl: null,
      group: amenityGroup,
      bookings: [],
      deletedAt: null,
    },
    {
      id: uuid('am05'),
      propertyId: IDS.mapleHeights,
      groupId: uuid('ag02'),
      name: 'Guest Suite',
      description: 'Furnished one-bedroom suite for overnight guests. Max 3 nights.',
      capacity: 2,
      imageUrl: null,
      group: { id: uuid('ag02'), name: 'Function Rooms' },
      bookings: [
        {
          id: uuid('bk05'),
          startDate: future(24),
          endDate: future(96),
          startTime: '15:00',
          endTime: '11:00',
          status: 'approved',
        },
      ],
      deletedAt: null,
    },
    {
      id: uuid('am06'),
      propertyId: IDS.mapleHeights,
      groupId: uuid('ag01'),
      name: 'Yoga Studio',
      description: 'Calm studio with mirrors, mats, and sound system. Ideal for classes.',
      capacity: 15,
      imageUrl: null,
      group: amenityGroup,
      bookings: [],
      deletedAt: null,
    },
    {
      id: uuid('am07'),
      propertyId: IDS.mapleHeights,
      groupId: uuid('ag01'),
      name: 'Sauna',
      description: 'Traditional Finnish dry sauna. 30-minute sessions.',
      capacity: 8,
      imageUrl: null,
      group: amenityGroup,
      bookings: [],
      deletedAt: null,
    },
    {
      id: uuid('am08'),
      propertyId: IDS.mapleHeights,
      groupId: uuid('ag02'),
      name: 'Theatre Room',
      description: 'Private cinema with 20 reclining seats and 4K projector.',
      capacity: 20,
      imageUrl: null,
      group: { id: uuid('ag02'), name: 'Function Rooms' },
      bookings: [],
      deletedAt: null,
    },
  ]);

  // =========================================================================
  // ANNOUNCEMENTS
  // =========================================================================
  store.seed('announcements', [
    {
      id: uuid('ann01'),
      propertyId: IDS.mapleHeights,
      title: 'Pool Maintenance — Temporary Closure',
      content:
        'The swimming pool will be closed March 25-27 for annual maintenance and deep cleaning. We apologize for the inconvenience.',
      priority: 'high',
      channels: ['web', 'email'],
      status: 'published',
      scheduledAt: null,
      publishedAt: ago(12),
      categoryId: uuid('anc01'),
      createdById: uuid('u02'),
      createdAt: ago(12),
      category: { id: uuid('anc01'), name: 'Maintenance' },
    },
    {
      id: uuid('ann02'),
      propertyId: IDS.mapleHeights,
      title: 'Fire Drill — March 28 at 10:00 AM',
      content:
        'A scheduled fire drill will take place on March 28th at 10:00 AM. All residents must evacuate to the designated assembly point in the parking lot.',
      priority: 'urgent',
      channels: ['web', 'email', 'sms'],
      status: 'published',
      scheduledAt: null,
      publishedAt: ago(24),
      categoryId: uuid('anc02'),
      createdById: uuid('u02'),
      createdAt: ago(24),
      category: { id: uuid('anc02'), name: 'Safety' },
    },
    {
      id: uuid('ann03'),
      propertyId: IDS.mapleHeights,
      title: 'Holiday Office Hours — Easter Weekend',
      content:
        'The management office will be closed Friday March 29 and Monday April 1. Emergency maintenance available 24/7 at 416-555-0999.',
      priority: 'normal',
      channels: ['web', 'email'],
      status: 'published',
      scheduledAt: null,
      publishedAt: ago(48),
      categoryId: uuid('anc03'),
      createdById: uuid('u02'),
      createdAt: ago(48),
      category: { id: uuid('anc03'), name: 'General' },
    },
    {
      id: uuid('ann04'),
      propertyId: IDS.mapleHeights,
      title: 'New Recycling Guidelines',
      content:
        'Starting April 1, all recyclables must be sorted into designated bins. Blue for paper, green for plastics, grey for glass. See the updated guide posted in each elevator lobby.',
      priority: 'normal',
      channels: ['web'],
      status: 'published',
      scheduledAt: null,
      publishedAt: ago(96),
      categoryId: uuid('anc03'),
      createdById: uuid('u02'),
      createdAt: ago(96),
      category: { id: uuid('anc03'), name: 'General' },
    },
    {
      id: uuid('ann05'),
      propertyId: IDS.mapleHeights,
      title: 'Spring Social BBQ — RSVP Open',
      content:
        'Join us for the annual Spring Social BBQ on the rooftop terrace! Food, drinks, and music. RSVP at the front desk or through the resident portal by April 10.',
      priority: 'low',
      channels: ['web', 'email', 'push'],
      status: 'scheduled',
      scheduledAt: future(72),
      publishedAt: null,
      categoryId: uuid('anc04'),
      createdById: uuid('u02'),
      createdAt: ago(8),
      category: { id: uuid('anc04'), name: 'Community' },
    },
    {
      id: uuid('ann06'),
      propertyId: IDS.mapleHeights,
      title: 'Elevator Modernization Update',
      content:
        'Phase 2 of the elevator modernization project is on track. Elevator B will be out of service April 15-30. Elevator A will remain operational.',
      priority: 'high',
      channels: ['web', 'email'],
      status: 'draft',
      scheduledAt: null,
      publishedAt: null,
      categoryId: uuid('anc01'),
      createdById: uuid('u02'),
      createdAt: ago(2),
      category: { id: uuid('anc01'), name: 'Maintenance' },
    },
    {
      id: uuid('ann07'),
      propertyId: IDS.mapleHeights,
      title: 'Package Room Policy Reminder',
      content:
        'Please collect your packages within 48 hours of notification. Uncollected perishable items will be disposed of after 24 hours.',
      priority: 'normal',
      channels: ['web'],
      status: 'published',
      scheduledAt: null,
      publishedAt: ago(168),
      categoryId: uuid('anc03'),
      createdById: uuid('u03'),
      createdAt: ago(168),
      category: { id: uuid('anc03'), name: 'General' },
    },
    {
      id: uuid('ann08'),
      propertyId: IDS.mapleHeights,
      title: 'Board Meeting Minutes — March 2026',
      content:
        'Minutes from the March board meeting are now available in the document library. Key topics: budget approval, elevator project update, summer amenity hours.',
      priority: 'low',
      channels: ['web'],
      status: 'published',
      scheduledAt: null,
      publishedAt: ago(72),
      categoryId: uuid('anc05'),
      createdById: uuid('u20'),
      createdAt: ago(72),
      category: { id: uuid('anc05'), name: 'Governance' },
    },
  ]);

  // =========================================================================
  // VISITORS
  // =========================================================================
  store.seed('visitors', [
    {
      id: uuid('vis01'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0101'),
      visitorName: 'John Smith',
      visitorType: 'visitor',
      arrivalAt: ago(0.5),
      departureAt: null,
      expectedDepartureAt: future(3),
      notifyResident: true,
      comments: 'Friend visiting for dinner',
      unit: { id: uuid('unit0101'), number: '101' },
    },
    {
      id: uuid('vis02'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0301'),
      visitorName: 'Mike Plumber',
      visitorType: 'contractor',
      arrivalAt: ago(1),
      departureAt: null,
      expectedDepartureAt: future(2),
      notifyResident: true,
      comments: 'Here to fix kitchen sink — MR-MH0001',
      unit: { id: uuid('unit0301'), number: '301' },
    },
    {
      id: uuid('vis03'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0402'),
      visitorName: 'Emily Chen',
      visitorType: 'real_estate_agent',
      arrivalAt: ago(0.25),
      departureAt: null,
      expectedDepartureAt: future(1),
      notifyResident: true,
      comments: 'Unit showing for potential buyer',
      unit: { id: uuid('unit0402'), number: '402' },
    },
    {
      id: uuid('vis04'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0204'),
      visitorName: 'Amazon Driver',
      visitorType: 'delivery_person',
      arrivalAt: ago(2),
      departureAt: ago(1.5),
      expectedDepartureAt: null,
      notifyResident: false,
      comments: 'Package drop-off',
      unit: { id: uuid('unit0204'), number: '204' },
    },
    {
      id: uuid('vis05'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0102'),
      visitorName: 'Dr. Sarah Kim',
      visitorType: 'visitor',
      arrivalAt: ago(4),
      departureAt: ago(2),
      expectedDepartureAt: null,
      notifyResident: true,
      comments: null,
      unit: { id: uuid('unit0102'), number: '102' },
    },
    {
      id: uuid('vis06'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0501'),
      visitorName: 'GreenTech HVAC',
      visitorType: 'contractor',
      arrivalAt: ago(24),
      departureAt: ago(20),
      expectedDepartureAt: null,
      notifyResident: true,
      comments: 'Annual HVAC inspection',
      unit: { id: uuid('unit0501'), number: '501' },
    },
    {
      id: uuid('vis07'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0303'),
      visitorName: 'Canada Post',
      visitorType: 'delivery_person',
      arrivalAt: ago(5),
      departureAt: ago(4.5),
      expectedDepartureAt: null,
      notifyResident: false,
      comments: 'Registered mail',
      unit: { id: uuid('unit0303'), number: '303' },
    },
    {
      id: uuid('vis08'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0201'),
      visitorName: 'Rebecca Taylor',
      visitorType: 'visitor',
      arrivalAt: ago(0.1),
      departureAt: null,
      expectedDepartureAt: future(4),
      notifyResident: true,
      comments: 'Overnight guest',
      unit: { id: uuid('unit0201'), number: '201' },
    },
  ]);

  // =========================================================================
  // EVENT TYPES & EVENTS
  // =========================================================================
  const eventTypes = [
    {
      id: uuid('et01'),
      name: 'Package Intake',
      slug: 'package_intake',
      icon: '📦',
      color: '#3B82F6',
      propertyId: IDS.mapleHeights,
    },
    {
      id: uuid('et02'),
      name: 'Visitor Entry',
      slug: 'visitor_entry',
      icon: '🚶',
      color: '#22C55E',
      propertyId: IDS.mapleHeights,
    },
    {
      id: uuid('et03'),
      name: 'Incident Report',
      slug: 'incident_report',
      icon: '⚠️',
      color: '#EF4444',
      propertyId: IDS.mapleHeights,
    },
    {
      id: uuid('et04'),
      name: 'Noise Complaint',
      slug: 'noise_complaint',
      icon: '🔊',
      color: '#F59E0B',
      propertyId: IDS.mapleHeights,
    },
    {
      id: uuid('et05'),
      name: 'Key Checkout',
      slug: 'key_checkout',
      icon: '🔑',
      color: '#8B5CF6',
      propertyId: IDS.mapleHeights,
    },
    {
      id: uuid('et06'),
      name: 'Cleaning Log',
      slug: 'cleaning_log',
      icon: '🧹',
      color: '#14B8A6',
      propertyId: IDS.mapleHeights,
    },
    {
      id: uuid('et07'),
      name: 'Parking Violation',
      slug: 'parking_violation',
      icon: '🚗',
      color: '#F97316',
      propertyId: IDS.mapleHeights,
    },
    {
      id: uuid('et08'),
      name: 'Shift Log',
      slug: 'shift_log',
      icon: '📝',
      color: '#6B7280',
      propertyId: IDS.mapleHeights,
    },
    {
      id: uuid('et09'),
      name: 'Fire Safety',
      slug: 'fire_safety',
      icon: '🔥',
      color: '#DC2626',
      propertyId: IDS.mapleHeights,
    },
    {
      id: uuid('et10'),
      name: 'Authorized Entry',
      slug: 'authorized_entry',
      icon: '🚪',
      color: '#6366F1',
      propertyId: IDS.mapleHeights,
    },
  ];
  store.seed('eventTypes', eventTypes);

  store.seed('events', [
    {
      id: uuid('ev01'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et01'),
      unitId: uuid('unit0101'),
      title: 'Amazon package for Unit 101',
      description: 'Large box, stored on Shelf A',
      status: 'open',
      priority: 'low',
      referenceNo: 'EVT-MH0001',
      customFields: {},
      createdById: uuid('u03'),
      createdAt: ago(0.5),
      closedAt: null,
      eventType: eventTypes[0],
      unit: { id: uuid('unit0101'), number: '101' },
    },
    {
      id: uuid('ev02'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et02'),
      unitId: uuid('unit0301'),
      title: 'Contractor visiting Unit 301',
      description: 'Plumber for maintenance request MR-MH0001',
      status: 'open',
      priority: 'medium',
      referenceNo: 'EVT-MH0002',
      customFields: {},
      createdById: uuid('u04'),
      createdAt: ago(1),
      closedAt: null,
      eventType: eventTypes[1],
      unit: { id: uuid('unit0301'), number: '301' },
    },
    {
      id: uuid('ev03'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et03'),
      unitId: null,
      title: 'Suspicious person in parking garage',
      description:
        'Individual observed trying car door handles in B2. Security responded, person left premises.',
      status: 'closed',
      priority: 'high',
      referenceNo: 'EVT-MH0003',
      customFields: {},
      createdById: uuid('u04'),
      createdAt: ago(6),
      closedAt: ago(5),
      eventType: eventTypes[2],
      unit: null,
    },
    {
      id: uuid('ev04'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et04'),
      unitId: uuid('unit0302'),
      title: 'Noise complaint — Unit 302',
      description: 'Loud music reported by Unit 301 at 11:30 PM. Resident warned.',
      status: 'closed',
      priority: 'medium',
      referenceNo: 'EVT-MH0004',
      customFields: {},
      createdById: uuid('u04'),
      createdAt: ago(18),
      closedAt: ago(17),
      eventType: eventTypes[3],
      unit: { id: uuid('unit0302'), number: '302' },
    },
    {
      id: uuid('ev05'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et06'),
      unitId: null,
      title: 'Lobby cleaning completed',
      description: 'Daily lobby and entrance area cleaned and mopped.',
      status: 'closed',
      priority: 'low',
      referenceNo: 'EVT-MH0005',
      customFields: {},
      createdById: uuid('u05'),
      createdAt: ago(3),
      closedAt: ago(2.5),
      eventType: eventTypes[5],
      unit: null,
    },
    {
      id: uuid('ev06'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et07'),
      unitId: null,
      title: 'Parking violation — Lot B',
      description:
        'Vehicle with plate XYZ-789 parked in visitor spot without permit. Warning issued.',
      status: 'open',
      priority: 'medium',
      referenceNo: 'EVT-MH0006',
      customFields: {},
      createdById: uuid('u04'),
      createdAt: ago(2),
      closedAt: null,
      eventType: eventTypes[6],
      unit: null,
    },
  ]);

  // =========================================================================
  // SHIFT LOG
  // =========================================================================
  store.seed('shiftLog', [
    {
      id: uuid('sl01'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et08'),
      title: 'Morning shift handoff',
      description:
        'All clear overnight. 2 packages received from late delivery. Lobby floors mopped. Elevator B had a brief alarm at 3 AM — reset successfully.',
      priority: 'normal',
      referenceNo: 'SL-MH0001',
      customFields: { category: 'general', pinned: false, readBy: [uuid('u03')] },
      createdById: uuid('u07'),
      createdAt: ago(8),
      eventType: { name: 'Shift Log' },
    },
    {
      id: uuid('sl02'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et08'),
      title: 'Guest parking issue — Lot B',
      description:
        'Resident in 402 complained about unknown vehicle in their assigned spot. Vehicle belongs to a guest of 401 — resolved after conversation.',
      priority: 'important',
      referenceNo: 'SL-MH0002',
      customFields: { category: 'parking', pinned: true, readBy: [] },
      createdById: uuid('u03'),
      createdAt: ago(4),
      eventType: { name: 'Shift Log' },
    },
    {
      id: uuid('sl03'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et08'),
      title: 'Fire alarm — false alarm',
      description:
        'Fire alarm triggered at 2:15 PM on floor 3 due to cooking smoke in unit 303. Fire dept notified and cleared. No evacuation needed.',
      priority: 'urgent',
      referenceNo: 'SL-MH0003',
      customFields: {
        category: 'security',
        pinned: true,
        readBy: [uuid('u02'), uuid('u03'), uuid('u04')],
      },
      createdById: uuid('u04'),
      createdAt: ago(12),
      eventType: { name: 'Shift Log' },
    },
    {
      id: uuid('sl04'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et08'),
      title: 'Delivery truck blocking entrance',
      description:
        'FedEx truck parked at main entrance for 45 minutes during morning rush. Asked to move to loading dock. Complied.',
      priority: 'normal',
      referenceNo: 'SL-MH0004',
      customFields: { category: 'general', pinned: false, readBy: [uuid('u03')] },
      createdById: uuid('u03'),
      createdAt: ago(28),
      eventType: { name: 'Shift Log' },
    },
    {
      id: uuid('sl05'),
      propertyId: IDS.mapleHeights,
      eventTypeId: uuid('et08'),
      title: 'Water leak in P1 parking',
      description:
        'Small water leak detected near pipe junction in P1 level. Superintendent notified. Maintenance scheduled for tomorrow morning.',
      priority: 'important',
      referenceNo: 'SL-MH0005',
      customFields: { category: 'maintenance', pinned: false, readBy: [uuid('u02'), uuid('u06')] },
      createdById: uuid('u04'),
      createdAt: ago(16),
      eventType: { name: 'Shift Log' },
    },
  ]);

  // =========================================================================
  // KEYS / FOBs
  // =========================================================================
  store.seed('keys', [
    {
      id: uuid('key01'),
      propertyId: IDS.mapleHeights,
      keyName: 'Master Building Key',
      keyNumber: 'MK-001',
      keyOwner: 'Management Office',
      category: 'master',
      status: 'available',
      notes: 'Stored in secure safe. Sign-out required.',
      createdById: uuid('u02'),
      createdAt: ago(2160),
      checkouts: [],
      activeCheckout: null,
      isOverdue: false,
    },
    {
      id: uuid('key02'),
      propertyId: IDS.mapleHeights,
      keyName: 'Pool Room Key',
      keyNumber: 'MK-002',
      keyOwner: 'Front Desk',
      category: 'common_area',
      status: 'checked_out',
      notes: null,
      createdById: uuid('u02'),
      createdAt: ago(2160),
      checkouts: [
        {
          id: uuid('kc01'),
          checkedOutTo: 'Tony DiMaggio',
          checkoutTime: ago(2),
          returnTime: null,
          expectedReturn: future(6),
          unitId: null,
        },
      ],
      activeCheckout: {
        id: uuid('kc01'),
        checkedOutTo: 'Tony DiMaggio',
        checkoutTime: ago(2),
        returnTime: null,
        expectedReturn: future(6),
      },
      isOverdue: false,
    },
    {
      id: uuid('key03'),
      propertyId: IDS.mapleHeights,
      keyName: 'Rooftop Access Key',
      keyNumber: 'MK-003',
      keyOwner: 'Front Desk',
      category: 'common_area',
      status: 'available',
      notes: 'Only for authorized maintenance staff',
      createdById: uuid('u02'),
      createdAt: ago(2160),
      checkouts: [],
      activeCheckout: null,
      isOverdue: false,
    },
    {
      id: uuid('key04'),
      propertyId: IDS.mapleHeights,
      keyName: 'Unit 301 Spare',
      keyNumber: 'UK-301',
      keyOwner: 'Unit 301 — Lisa Wang',
      category: 'unit',
      status: 'available',
      notes: 'Emergency spare key',
      createdById: uuid('u02'),
      createdAt: ago(1800),
      checkouts: [],
      activeCheckout: null,
      isOverdue: false,
    },
    {
      id: uuid('key05'),
      propertyId: IDS.mapleHeights,
      keyName: 'FOB #1001',
      keyNumber: 'FOB-1001',
      keyOwner: 'Lisa Wang — Unit 101',
      category: 'fob',
      status: 'available',
      notes: 'Active FOB',
      createdById: uuid('u02'),
      createdAt: ago(1800),
      checkouts: [],
      activeCheckout: null,
      isOverdue: false,
    },
    {
      id: uuid('key06'),
      propertyId: IDS.mapleHeights,
      keyName: 'Garage Clicker #201',
      keyNumber: 'GC-201',
      keyOwner: 'David Kumar — Unit 204',
      category: 'garage_clicker',
      status: 'available',
      notes: null,
      createdById: uuid('u02'),
      createdAt: ago(1200),
      checkouts: [],
      activeCheckout: null,
      isOverdue: false,
    },
    {
      id: uuid('key07'),
      propertyId: IDS.mapleHeights,
      keyName: 'Electrical Room Key',
      keyNumber: 'MK-004',
      keyOwner: 'Superintendent',
      category: 'common_area',
      status: 'checked_out',
      notes: 'Restricted access',
      createdById: uuid('u02'),
      createdAt: ago(2160),
      checkouts: [
        {
          id: uuid('kc02'),
          checkedOutTo: 'Priya Sharma',
          checkoutTime: ago(48),
          returnTime: null,
          expectedReturn: ago(24),
          unitId: null,
        },
      ],
      activeCheckout: {
        id: uuid('kc02'),
        checkedOutTo: 'Priya Sharma',
        checkoutTime: ago(48),
        returnTime: null,
        expectedReturn: ago(24),
      },
      isOverdue: true,
    },
  ]);

  // =========================================================================
  // PARKING
  // =========================================================================
  store.seed('parkingPermits', [
    {
      id: uuid('pp01'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0101'),
      vehicleId: uuid('v01'),
      permitTypeId: uuid('pt01'),
      referenceNumber: 'PRK-20260101-0001',
      licensePlate: 'ABCD 123',
      validFrom: ago(2160),
      validUntil: future(4320),
      status: 'active',
      autoRenew: true,
      notes: 'Spot B-01',
      createdById: uuid('u02'),
      createdAt: ago(2160),
      unit: { id: uuid('unit0101'), number: '101' },
      permitType: { id: uuid('pt01'), name: 'Residential — Annual' },
    },
    {
      id: uuid('pp02'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0301'),
      vehicleId: uuid('v02'),
      permitTypeId: uuid('pt01'),
      referenceNumber: 'PRK-20260101-0002',
      licensePlate: 'EFGH 456',
      validFrom: ago(1800),
      validUntil: future(2880),
      status: 'active',
      autoRenew: false,
      notes: 'Spot B-15',
      createdById: uuid('u02'),
      createdAt: ago(1800),
      unit: { id: uuid('unit0301'), number: '301' },
      permitType: { id: uuid('pt01'), name: 'Residential — Annual' },
    },
    {
      id: uuid('pp03'),
      propertyId: IDS.mapleHeights,
      unitId: uuid('unit0402'),
      vehicleId: uuid('v03'),
      permitTypeId: uuid('pt02'),
      referenceNumber: 'PRK-20260301-0003',
      licensePlate: 'IJKL 789',
      validFrom: ago(480),
      validUntil: future(240),
      status: 'active',
      autoRenew: false,
      notes: null,
      createdById: uuid('u02'),
      createdAt: ago(480),
      unit: { id: uuid('unit0402'), number: '402' },
      permitType: { id: uuid('pt02'), name: 'Residential — Monthly' },
    },
  ]);
  store.seed('parkingViolations', [
    {
      id: uuid('pv01'),
      propertyId: IDS.mapleHeights,
      licensePlate: 'XYZ 789',
      location: 'Lot B — Visitor Parking',
      violationType: 'No permit',
      status: 'open',
      observedAt: ago(2),
      createdAt: ago(2),
    },
    {
      id: uuid('pv02'),
      propertyId: IDS.mapleHeights,
      licensePlate: 'MNO 456',
      location: 'P1 — Reserved',
      violationType: 'Wrong area',
      status: 'resolved',
      observedAt: ago(72),
      createdAt: ago(72),
    },
  ]);

  // =========================================================================
  // TRAINING
  // =========================================================================
  store.seed('training', [
    {
      id: uuid('tr01'),
      propertyId: IDS.mapleHeights,
      courseCode: 'TRN-FD001',
      title: 'Front Desk Essentials',
      description:
        'Core training for new front desk staff covering package handling, visitor management, and communication protocols.',
      estimatedDurationMinutes: 180,
      category: 'onboarding',
      difficulty: 'beginner',
      passThreshold: 70,
      mandatory: true,
      status: 'published',
      createdById: uuid('u02'),
      createdAt: ago(1440),
      modules: [
        { id: uuid('tm01'), title: 'Reception Basics', sortOrder: 1 },
        { id: uuid('tm02'), title: 'Package Handling', sortOrder: 2 },
        { id: uuid('tm03'), title: 'Visitor Protocol', sortOrder: 3 },
      ],
      learningPathCourses: [{ learningPath: { id: uuid('lp01'), name: 'New Hire Onboarding' } }],
      enrollmentCount: 12,
      completionRate: 75,
    },
    {
      id: uuid('tr02'),
      propertyId: IDS.mapleHeights,
      courseCode: 'TRN-SC001',
      title: 'Security Procedures',
      description:
        'Comprehensive security training covering incident reporting, patrol routes, and emergency response.',
      estimatedDurationMinutes: 240,
      category: 'security',
      difficulty: 'intermediate',
      passThreshold: 80,
      mandatory: true,
      status: 'published',
      createdById: uuid('u02'),
      createdAt: ago(1200),
      modules: [
        { id: uuid('tm04'), title: 'Incident Response', sortOrder: 1 },
        { id: uuid('tm05'), title: 'Patrol Procedures', sortOrder: 2 },
      ],
      learningPathCourses: [{ learningPath: { id: uuid('lp01'), name: 'New Hire Onboarding' } }],
      enrollmentCount: 8,
      completionRate: 88,
    },
    {
      id: uuid('tr03'),
      propertyId: IDS.mapleHeights,
      courseCode: 'TRN-FS001',
      title: 'Fire Safety & Evacuation',
      description:
        'Annual fire safety refresher including evacuation procedures and fire extinguisher use.',
      estimatedDurationMinutes: 60,
      category: 'safety',
      difficulty: 'beginner',
      passThreshold: 90,
      mandatory: true,
      status: 'published',
      createdById: uuid('u02'),
      createdAt: ago(720),
      modules: [{ id: uuid('tm06'), title: 'Fire Safety Basics', sortOrder: 1 }],
      learningPathCourses: [],
      enrollmentCount: 18,
      completionRate: 94,
    },
    {
      id: uuid('tr04'),
      propertyId: IDS.mapleHeights,
      courseCode: 'TRN-CS001',
      title: 'Customer Service Excellence',
      description: 'Best practices for resident communication and conflict resolution.',
      estimatedDurationMinutes: 120,
      category: 'professional_development',
      difficulty: 'beginner',
      passThreshold: 70,
      mandatory: false,
      status: 'published',
      createdById: uuid('u02'),
      createdAt: ago(480),
      modules: [
        { id: uuid('tm07'), title: 'Communication Skills', sortOrder: 1 },
        { id: uuid('tm08'), title: 'Conflict Resolution', sortOrder: 2 },
      ],
      learningPathCourses: [],
      enrollmentCount: 10,
      completionRate: 60,
    },
  ]);

  // =========================================================================
  // BILLING
  // =========================================================================
  store.seed('billing', [
    {
      id: uuid('bill01'),
      propertyId: IDS.mapleHeights,
      tier: 'Professional',
      status: 'active',
      billingCycle: 'monthly',
      pricePerUnit: 4.5,
      periodStart: ago(720),
      periodEnd: future(24),
      nextBillingDate: future(24),
      stripeCustomerId: 'cus_demo_maple',
      stripeSubscriptionId: 'sub_demo_maple',
      trialEndsAt: null,
      usage: { unitCount: 200, userCount: 14, maxUnits: 500, maxUsers: 50 },
      features: [
        'Unlimited events',
        'Package tracking',
        'Maintenance requests',
        'Amenity booking',
        'Multi-channel notifications',
        'Custom reports',
        'API access',
        'Priority support',
      ],
    },
  ]);

  // =========================================================================
  // COMPLIANCE
  // =========================================================================
  store.seed('compliance', [
    {
      id: uuid('comp01'),
      propertyId: IDS.mapleHeights,
      overallScore: 91,
      frameworks: {
        PIPEDA: { status: 'compliant', completionPercentage: 98, lastAuditDate: ago(360) },
        'SOC 2': { status: 'compliant', completionPercentage: 95, lastAuditDate: ago(720) },
        'ISO 27001': { status: 'compliant', completionPercentage: 92, lastAuditDate: ago(1080) },
        'ISO 27701': { status: 'compliant', completionPercentage: 90, lastAuditDate: ago(1080) },
        GDPR: { status: 'compliant', completionPercentage: 96, lastAuditDate: ago(360) },
        HIPAA: { status: 'at_risk', completionPercentage: 78, lastAuditDate: ago(1440) },
        'ISO 9001': { status: 'compliant', completionPercentage: 88, lastAuditDate: ago(1080) },
        'ISO 27017': { status: 'compliant', completionPercentage: 85, lastAuditDate: ago(1080) },
      },
      recentViolations: [
        {
          violationType: 'HIPAA — Missing BAA for one sub-processor',
          severity: 'medium',
          detectedAt: ago(168),
          remediation: 'BAA under review with legal team. Expected resolution by April 1.',
        },
      ],
    },
  ]);

  // =========================================================================
  // REPORTS (available report types)
  // =========================================================================
  store.seed('reports', [
    { type: 'package_activity', name: 'Package Activity Report' },
    { type: 'maintenance_summary', name: 'Maintenance Summary' },
    { type: 'security_incidents', name: 'Security Incident Report' },
    { type: 'amenity_usage', name: 'Amenity Usage Report' },
    { type: 'resident_directory', name: 'Resident Directory Export' },
    { type: 'visitor_log', name: 'Visitor Log Report' },
    { type: 'key_inventory', name: 'Key/FOB Inventory' },
    { type: 'parking_permits', name: 'Parking Permit Report' },
    { type: 'financial_summary', name: 'Financial Summary' },
    { type: 'training_compliance', name: 'Training Compliance' },
    { type: 'shift_log_summary', name: 'Shift Log Summary' },
    { type: 'building_analytics', name: 'Building Analytics' },
  ]);

  // =========================================================================
  // DASHBOARD (pre-computed KPIs)
  // =========================================================================
  store.seed('dashboard', [
    {
      propertyId: IDS.mapleHeights,
      kpis: {
        unreleasedPackages: 8,
        activeVisitors: 3,
        openMaintenanceRequests: 5,
        todayEvents: 2,
        pendingBookingApprovals: 1,
        unreadAnnouncements: 4,
        overdueMaintenanceRequests: 1,
        monthlyPackageVolume: 145,
        avgResolutionTimeHours: 18,
      },
      recentActivity: [
        {
          id: uuid('ra01'),
          type: 'Package Intake',
          title: 'Amazon package for Unit 101',
          unit: '101',
          status: 'unreleased',
          createdAt: ago(0.5),
        },
        {
          id: uuid('ra02'),
          type: 'Visitor Entry',
          title: 'Contractor — Mike Plumber',
          unit: '301',
          status: 'active',
          createdAt: ago(1),
        },
        {
          id: uuid('ra03'),
          type: 'Maintenance',
          title: 'No heating in Unit 102',
          unit: '102',
          status: 'open',
          createdAt: ago(3),
        },
        {
          id: uuid('ra04'),
          type: 'Announcement',
          title: 'Pool Maintenance — Temp Closure',
          unit: null,
          status: 'published',
          createdAt: ago(12),
        },
        {
          id: uuid('ra05'),
          type: 'Parking Violation',
          title: 'No permit — Lot B',
          unit: null,
          status: 'open',
          createdAt: ago(2),
        },
        {
          id: uuid('ra06'),
          type: 'Shift Log',
          title: 'Fire alarm — false alarm',
          unit: null,
          status: 'resolved',
          createdAt: ago(12),
        },
        {
          id: uuid('ra07'),
          type: 'Key Checkout',
          title: 'Pool Room Key — Tony DiMaggio',
          unit: null,
          status: 'checked_out',
          createdAt: ago(2),
        },
        {
          id: uuid('ra08'),
          type: 'Package Released',
          title: 'FedEx package for Unit 201',
          unit: '201',
          status: 'released',
          createdAt: ago(44),
        },
        {
          id: uuid('ra09'),
          type: 'Maintenance Resolved',
          title: 'Toilet running — Unit 201',
          unit: '201',
          status: 'resolved',
          createdAt: ago(144),
        },
        {
          id: uuid('ra10'),
          type: 'Visitor Signed Out',
          title: 'GreenTech HVAC',
          unit: '501',
          status: 'signed_out',
          createdAt: ago(20),
        },
      ],
    },
  ]);

  // =========================================================================
  // SETTINGS
  // =========================================================================
  store.seed('settings', [
    {
      propertyId: IDS.mapleHeights,
      general: {
        propertyName: 'Maple Heights Condominiums',
        address: '100 Maple Avenue, Toronto, ON M5V 2H1',
        timezone: 'America/Toronto',
        language: 'en',
        dateFormat: 'YYYY-MM-DD',
        timeFormat: '12h',
      },
      notifications: {
        emailEnabled: true,
        smsEnabled: true,
        pushEnabled: true,
        defaultChannel: 'email',
      },
      security: { mfaRequired: false, sessionTimeout: 480, passwordMinLength: 8, loginAttempts: 5 },
      branding: {
        accentColor: '#1e40af',
        logo: null,
        welcomeMessage: 'Welcome to Maple Heights Condominiums!',
      },
    },
  ]);

  // =========================================================================
  // BUILDING DIRECTORY (placeholder)
  // =========================================================================
  store.seed('buildingDirectory', [
    {
      id: uuid('bd01'),
      propertyId: IDS.mapleHeights,
      name: 'Management Office',
      phone: '+1-416-555-0100',
      email: 'office@mapleheights.ca',
      hours: 'Mon-Fri 9:00 AM - 6:00 PM',
      category: 'management',
    },
    {
      id: uuid('bd02'),
      propertyId: IDS.mapleHeights,
      name: '24/7 Emergency',
      phone: '+1-416-555-0999',
      email: 'emergency@mapleheights.ca',
      hours: '24/7',
      category: 'emergency',
    },
    {
      id: uuid('bd03'),
      propertyId: IDS.mapleHeights,
      name: 'Concierge Desk',
      phone: '+1-416-555-0101',
      email: 'concierge@mapleheights.ca',
      hours: '24/7',
      category: 'front_desk',
    },
    {
      id: uuid('bd04'),
      propertyId: IDS.mapleHeights,
      name: 'Superintendent',
      phone: '+1-416-555-0106',
      email: 'super@mapleheights.ca',
      hours: 'Mon-Fri 8:00 AM - 5:00 PM',
      category: 'maintenance',
    },
  ]);

  // =========================================================================
  // DIGITAL SIGNAGE (placeholder)
  // =========================================================================
  store.seed('digitalSignage', [
    {
      id: uuid('ds01'),
      propertyId: IDS.mapleHeights,
      name: 'Lobby Display',
      location: 'Main Lobby',
      status: 'active',
      content: 'Pool closed March 25-27 for maintenance',
      lastUpdated: ago(12),
    },
    {
      id: uuid('ds02'),
      propertyId: IDS.mapleHeights,
      name: 'Elevator B Screen',
      location: 'Elevator B',
      status: 'active',
      content: 'Fire Drill March 28 — 10:00 AM',
      lastUpdated: ago(24),
    },
  ]);

  // =========================================================================
  // AI ANALYTICS (pre-computed)
  // =========================================================================
  store.seed('aiAnalytics', [
    {
      propertyId: IDS.mapleHeights,
      healthScore: 87,
      trend: 'up',
      factors: [
        { name: 'Maintenance Backlog', score: 82, weight: 0.3 },
        { name: 'Package Handling', score: 94, weight: 0.25 },
        { name: 'SLA Compliance', score: 88, weight: 0.25 },
        { name: 'Open Issues', score: 80, weight: 0.2 },
      ],
      packageDeliveryTrend: [
        { period: 'Week 1', count: 42, avgDeliveryHours: 3.5 },
        { period: 'Week 2', count: 38, avgDeliveryHours: 4.2 },
        { period: 'Week 3', count: 45, avgDeliveryHours: 3.1 },
        { period: 'Week 4', count: 35, avgDeliveryHours: 3.8 },
      ],
      maintenanceSlaCompliance: 88,
    },
  ]);
}
